#!/usr/bin/bash

function set_log_mode {
  if getent passwd oracle > /dev/null; then
    # check log_mode
    # select log_mode from v$database;
    # change oracle databse mode to archive log mode.
    local mode=$1
    if [ $mode == "archivelog" ]; then
      su - oracle -c "echo shutdown immediate; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "echo startup mount; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "ALTER DATABASE ARCHIVELOG; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "ALTER DATABASE OPEN; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
    elif [ $mode == "noarchivelog" ]; then
      su - oracle -c "echo shutdown immediate; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "echo startup mount; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "ALTER DATABASE NOARCHIVELOG; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
      su - oracle -c "ALTER DATABASE OPEN; | /opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as sysdba"
    else
      echo "unkown log_mode" >&2
      return 1
    fi
  fi
}
set_log_mode $@
